import type { ReactNode } from 'react';
import Scene from '../engine/Scene';
import type { SceneData } from '../engine/geometry';
import Icon from '../components/Icon';

export function GameLayout({ kind, title, description, data, paused, children, sceneLabel }: { kind: string; title: string; description: string; data?: SceneData; paused?: boolean; children: ReactNode; sceneLabel?: string }) {
  return <div className="game-layout" data-game-kind={kind}><div className="scene-column"><Scene kind={kind} data={data} label={sceneLabel || title} paused={paused} /><div className="mission-brief"><span className="eyebrow">YOUR MISSION</span><h2>{title}</h2><p>{description}</p></div></div><fieldset disabled={paused} className="game-controls" aria-label="Mission controls">{children}</fieldset></div>;
}
export function Stat({ label, value, icon, accent }: { label: string; value: string | number; icon?: string; accent?: boolean }) { return <div className={`game-stat ${accent ? 'accent' : ''}`}>{icon && <Icon name={icon} />}<div><span>{label}</span><strong>{value}</strong></div></div>; }
export function Stats({ children }: { children: ReactNode }) { return <div className="game-stats">{children}</div>; }
export function Notice({ children, tone = 'info' }: { children: ReactNode; tone?: 'info' | 'success' | 'warning' }) { return <div className={`notice ${tone}`} role="status"><Icon name={tone === 'success' ? 'check' : tone === 'warning' ? 'help' : 'info'} size={18} /><span>{children}</span></div>; }
export function Meter({ label, value, max = 100, color = 'var(--accent)', suffix = '%' }: { label: string; value: number; max?: number; color?: string; suffix?: string }) { return <div className="meter"><div><span>{label}</span><strong>{Math.round(value)}{suffix}</strong></div><div className="meter-track" role="progressbar" aria-label={label} aria-valuenow={Math.max(0, Math.min(max, value))} aria-valuemax={max} aria-valuemin={0}><i style={{ width: `${Math.max(0, Math.min(100, value / max * 100))}%`, background: color }} /></div></div>; }
export function StepDots({ total, current }: { total: number; current: number }) { return <div className="step-dots" aria-label={`Step ${Math.min(current + 1, total)} of ${total}`}>{Array.from({ length: total }, (_, i) => <span key={i} className={i < current ? 'done' : i === current ? 'current' : ''}>{i < current ? <Icon name="check" size={12} /> : i + 1}</span>)}</div>; }
export function Counter({ label, value, min = 0, max = 20, onChange, step = 1 }: { label: string; value: number; min?: number; max?: number; step?: number; onChange: (v: number) => void }) { return <div className="counter"><span>{label}</span><div><button className="icon-button" aria-label={`Decrease ${label}`} disabled={value <= min} onClick={() => onChange(Math.max(min, value - step))}><Icon name="minus" size={16} /></button><output>{value}</output><button className="icon-button" aria-label={`Increase ${label}`} disabled={value >= max} onClick={() => onChange(Math.min(max, value + step))}><Icon name="plus" size={16} /></button></div></div>; }
export function Action({ children, onClick, disabled = false, secondary = false }: { children: ReactNode; onClick: () => void; disabled?: boolean; secondary?: boolean }) { return <button className={`btn ${secondary ? 'secondary' : 'primary'}`} disabled={disabled} onClick={onClick}>{children}</button>; }
